name: Nightly zoning tile refresh

on:
  schedule:
    - cron: '7 9 * * *'             # 02:07 PT
  workflow_dispatch:

jobs:
  bake-tiles:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Install GDAL • Tippecanoe • Node
      run: |
        sudo apt-get update -y
        sudo apt-get install -y gdal-bin tippecanoe nodejs npm

    # 1 ▸ Fetch zoning polygons as WGS-84 GeoJSON
    - name: Download zoning GeoJSON (EPSG 4326)
      run: |
        curl -sSL -o zoning4326.geojson \
          "https://gisservices.surrey.ca/arcgis/rest/services/OpenData/MapServer/239/query?where=1=1&outFields=*&outSR=4326&f=geojson"

    # 2 ▸ Build PMTiles
    - name: Build PMTiles
      run: |
        rm -f zoning.pmtiles
        tippecanoe -Z10 -z18 --force \
          -l zone \                       # layer is now called “zone”
          --drop-densest-as-needed \
          -o zoning.pmtiles zoning4326.geojson

    # 2·a ▸ (optional) Inspect the archive we just created
    - name: Inspect PMTiles header
      run: |
        curl -sL \
          https://github.com/protomaps/pmtiles/releases/latest/download/pmtiles-linux \
          -o pmtiles && chmod +x pmtiles
        ./pmtiles info zoning.pmtiles | head      # prints layer list & bounds
        # the first 10 lines are enough for a quick sanity-check

    # 3 ▸ Commit & push only if the file changed
    - name: Commit & push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name  "Tile Bot"
        git config user.email "bot@users.noreply.github.com"
        git add zoning.pmtiles
        if ! git diff --cached --quiet; then
          git commit -m "Nightly zoning tiles $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          git push origin HEAD:main
        else
          echo "No changes in zoning.pmtiles"
        fi
