name: Nightly zoning tile refresh
on:
  schedule:    # 02:07 Vancouver time daily
    - cron: "7 9 * * *"
  workflow_dispatch:

jobs:
  bake-tiles:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repo that holds /tiles
    - uses: actions/checkout@v4
      with:
        persist-credentials: false   # we'll push via token

    # 2. Install GDAL + mbutil
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gdal-bin python3-pip
        pip install mbutil

    # 3. Download latest zoning GeoJSON
    - name: Fetch zoning polygons
      run: |
        curl -L -o zoning.geojson \
        "https://gisservices.surrey.ca/arcgis/rest/services/OpenData/MapServer/239/query?where=1=1&outFields=*&outSR=3857&f=geojson"

    # 4. Reproject to EPSG:3857 GeoPackage (vector)
    - name: Reproject to Web Mercator
      run: |
        ogr2ogr -t_srs EPSG:3857 zoning3857.gpkg zoning.geojson

    # 5. Rasterise to GeoTIFF (pixel size ~2 m, 1 band; burn 1)
    - name: Rasterize to GeoTIFF
      run: |
        gdal_rasterize \
          -burn 1 \
          -tr 2 2 \
          -te -13651500 6230000 -13580000 6290000 \
          -ot Byte \
          -of GTiff \
          zoning3857.gpkg \
          zoning.tif

    # 6. Generate XYZ PNG tiles (zoom 10-18)
    - name: Generate XYZ tiles
      run: |
        mkdir -p tiles
        gdal2tiles.py -z 10-18 -w none -r bilinear \
          --processes=4 zoning.tif tiles/
